name: Pnpm Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:

  build:

    # Runs on the latest Ubuntu instances available
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push version
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pnpm:node-lts-1.0.2

    - name: Build and push latest version
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pnpm:latest

    - name: push README to Dockerhub
      uses: christian-korneck/update-container-description-action@v1
      env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      with:
          destination_container_repo: ${{ secrets.DOCKER_HUB_USERNAME }}/pnpm
          provider: dockerhub
          short_description: 'This image can be used in Google Cloud Build and Gitlab CI if you need an image with pnpm'
          readme_file: 'README.md'
